/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as VerifyRouteRouteImport } from './routes/verify/route'
import { Route as SignerRouteRouteImport } from './routes/signer/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignerIndexRouteImport } from './routes/signer/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VerifyCredentialRefRouteImport } from './routes/verify/$credentialRef'
import { Route as PostsPostIdRouteImport } from './routes/posts/$postId'
import { Route as AdminSucess_issueRouteImport } from './routes/admin/sucess_issue'
import { Route as AdminIssue_credentialRouteImport } from './routes/admin/issue_credential'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCredentialsRouteImport } from './routes/admin/credentials'
import { Route as AdminStudentsRouteRouteImport } from './routes/admin/students/route'
import { Route as AdminStudentsIndexRouteImport } from './routes/admin/students/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRouteRoute = VerifyRouteRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SignerRouteRoute = SignerRouteRouteImport.update({
  id: '/signer',
  path: '/signer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignerIndexRoute = SignerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignerRouteRoute,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const VerifyCredentialRefRoute = VerifyCredentialRefRouteImport.update({
  id: '/$credentialRef',
  path: '/$credentialRef',
  getParentRoute: () => VerifyRouteRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSucess_issueRoute = AdminSucess_issueRouteImport.update({
  id: '/sucess_issue',
  path: '/sucess_issue',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminIssue_credentialRoute = AdminIssue_credentialRouteImport.update({
  id: '/issue_credential',
  path: '/issue_credential',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCredentialsRoute = AdminCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStudentsRouteRoute = AdminStudentsRouteRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStudentsIndexRoute = AdminStudentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminStudentsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/signer': typeof SignerRouteRouteWithChildren
  '/verify': typeof VerifyRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/students': typeof AdminStudentsRouteRouteWithChildren
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/issue_credential': typeof AdminIssue_credentialRoute
  '/admin/sucess_issue': typeof AdminSucess_issueRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/verify/$credentialRef': typeof VerifyCredentialRefRoute
  '/admin/': typeof AdminIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/signer/': typeof SignerIndexRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/verify': typeof VerifyRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/issue_credential': typeof AdminIssue_credentialRoute
  '/admin/sucess_issue': typeof AdminSucess_issueRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/verify/$credentialRef': typeof VerifyCredentialRefRoute
  '/admin': typeof AdminIndexRoute
  '/posts': typeof PostsIndexRoute
  '/signer': typeof SignerIndexRoute
  '/admin/students': typeof AdminStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/signer': typeof SignerRouteRouteWithChildren
  '/verify': typeof VerifyRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/students': typeof AdminStudentsRouteRouteWithChildren
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/issue_credential': typeof AdminIssue_credentialRoute
  '/admin/sucess_issue': typeof AdminSucess_issueRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/verify/$credentialRef': typeof VerifyCredentialRefRoute
  '/admin/': typeof AdminIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/signer/': typeof SignerIndexRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/signer'
    | '/verify'
    | '/login'
    | '/admin/students'
    | '/admin/credentials'
    | '/admin/dashboard'
    | '/admin/issue_credential'
    | '/admin/sucess_issue'
    | '/posts/$postId'
    | '/verify/$credentialRef'
    | '/admin/'
    | '/posts/'
    | '/signer/'
    | '/admin/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/verify'
    | '/login'
    | '/admin/credentials'
    | '/admin/dashboard'
    | '/admin/issue_credential'
    | '/admin/sucess_issue'
    | '/posts/$postId'
    | '/verify/$credentialRef'
    | '/admin'
    | '/posts'
    | '/signer'
    | '/admin/students'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/signer'
    | '/verify'
    | '/login'
    | '/admin/students'
    | '/admin/credentials'
    | '/admin/dashboard'
    | '/admin/issue_credential'
    | '/admin/sucess_issue'
    | '/posts/$postId'
    | '/verify/$credentialRef'
    | '/admin/'
    | '/posts/'
    | '/signer/'
    | '/admin/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SignerRouteRoute: typeof SignerRouteRouteWithChildren
  VerifyRouteRoute: typeof VerifyRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signer': {
      id: '/signer'
      path: '/signer'
      fullPath: '/signer'
      preLoaderRoute: typeof SignerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signer/': {
      id: '/signer/'
      path: '/'
      fullPath: '/signer/'
      preLoaderRoute: typeof SignerIndexRouteImport
      parentRoute: typeof SignerRouteRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/verify/$credentialRef': {
      id: '/verify/$credentialRef'
      path: '/$credentialRef'
      fullPath: '/verify/$credentialRef'
      preLoaderRoute: typeof VerifyCredentialRefRouteImport
      parentRoute: typeof VerifyRouteRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sucess_issue': {
      id: '/admin/sucess_issue'
      path: '/sucess_issue'
      fullPath: '/admin/sucess_issue'
      preLoaderRoute: typeof AdminSucess_issueRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/issue_credential': {
      id: '/admin/issue_credential'
      path: '/issue_credential'
      fullPath: '/admin/issue_credential'
      preLoaderRoute: typeof AdminIssue_credentialRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/credentials': {
      id: '/admin/credentials'
      path: '/credentials'
      fullPath: '/admin/credentials'
      preLoaderRoute: typeof AdminCredentialsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/students/': {
      id: '/admin/students/'
      path: '/'
      fullPath: '/admin/students/'
      preLoaderRoute: typeof AdminStudentsIndexRouteImport
      parentRoute: typeof AdminStudentsRouteRoute
    }
  }
}

interface AdminStudentsRouteRouteChildren {
  AdminStudentsIndexRoute: typeof AdminStudentsIndexRoute
}

const AdminStudentsRouteRouteChildren: AdminStudentsRouteRouteChildren = {
  AdminStudentsIndexRoute: AdminStudentsIndexRoute,
}

const AdminStudentsRouteRouteWithChildren =
  AdminStudentsRouteRoute._addFileChildren(AdminStudentsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminStudentsRouteRoute: typeof AdminStudentsRouteRouteWithChildren
  AdminCredentialsRoute: typeof AdminCredentialsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminIssue_credentialRoute: typeof AdminIssue_credentialRoute
  AdminSucess_issueRoute: typeof AdminSucess_issueRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminStudentsRouteRoute: AdminStudentsRouteRouteWithChildren,
  AdminCredentialsRoute: AdminCredentialsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminIssue_credentialRoute: AdminIssue_credentialRoute,
  AdminSucess_issueRoute: AdminSucess_issueRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface SignerRouteRouteChildren {
  SignerIndexRoute: typeof SignerIndexRoute
}

const SignerRouteRouteChildren: SignerRouteRouteChildren = {
  SignerIndexRoute: SignerIndexRoute,
}

const SignerRouteRouteWithChildren = SignerRouteRoute._addFileChildren(
  SignerRouteRouteChildren,
)

interface VerifyRouteRouteChildren {
  VerifyCredentialRefRoute: typeof VerifyCredentialRefRoute
}

const VerifyRouteRouteChildren: VerifyRouteRouteChildren = {
  VerifyCredentialRefRoute: VerifyCredentialRefRoute,
}

const VerifyRouteRouteWithChildren = VerifyRouteRoute._addFileChildren(
  VerifyRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SignerRouteRoute: SignerRouteRouteWithChildren,
  VerifyRouteRoute: VerifyRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
